Feature/AW-34 | Teacher - Class management
phunguyen58/advanced-web pull request #15
Opened 2024-01-01 09:22 UTC by anhkhoajjo

2024-01-01 09:22 UTC, anhkhoajjo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Teacher - Class management](https://trello.com/c/okZCK8KF/34-teacher-class-management)

2024-01-01 14:29 UTC, huykevin2002 commented on src/main/java/com/ptudw/web/web/rest/CourseResource.java
> +        Optional<Course> course = courseService.findOne(userId);
The method is "getJoinedCoursesByUserId", but I see that it returns only one course, it is okay?

2024-01-01 14:32 UTC, huykevin2002 commented on src/main/webapp/app/shared/components/class-card/class-card.tsx
> +      <img className="aw-card-header-image" src="../../../../content/images/title-area-left-background-holiday.jpg" alt="" />
It must be `src="content/images/title-area-left-background-holiday.jpg"`

2024-01-01 14:33 UTC, huykevin2002 requested changes
Huy's Code Review

2024-01-02 14:51 UTC, huykevin2002 approved these changes

2024-01-02 14:52 UTC, merged